name: Build2

on:
  push:
    branches:
      - '*/*'
      - master
      - main
  workflow_dispatch:
    inputs:
      reports:
        description: 'Generate Reports'
        type: boolean
        required: false
        default: 'false'

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-18.04
    env:
      CI: true
      GITHUB_BRANCH: ${{ github.ref }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: build project
        run: |
          echo "Log level: $GITHUB_BRANCH"
          echo "Tags: $GITHUB_TOKEN"
          echo "events ${{ github.event.inputs.reports }}"
      - if: github.event.inputs.reports == 'true'
        name: build reports
        run: echo "oh my!"
      
        
